### ISSUE TITLE
OpenStack Compatible

### ISSUE THREAD

**Issue by ghost** [pitchpoint-solutions/sfs#1]
Hi,

Is this software [compatible](https://www.openstack.org/brand/interop/) with OpenStack?
As far as i know OpenStack reference implementations must pass [Temptest](https://git.openstack.org/cgit/openstack/tempest)?

Thanks

**Comment by P4Awd** [comment]
Hi ui4j,

The openstack swift web api sfs presents is definitely not intended to be a reference implementation. Simply compatible enough for tools like [cyberduck](https://cyberduck.io) to work. A Tempest run at this point would not pass but if someone extended the swift web api component to pass a Tempest run we'd be thrilled.
